### ISSUE TITLE
Niewyświetlające się zdjęcia na ebay.pl

### ISSUE THREAD

**Issue by DyG121** [maciejtarmas/AlleBlock#10]
Od kilku dni używam wtyczki. Dziś zauważyłem, że na ebay.pl nie wyświetlają się zdjęcia przedmiotów na aukcji. Zdjęcia wyświetlają się jako miniatury na listach przedmiotów, jednak po wejściu w konkretną aukcję zdjęcia już się nie ładują. Sprawdziłem na innych stronach ebay i problem występuje tylko na ebay.pl.

Przykładowy screen.
![schowek01](https://user-images.githubusercontent.com/33463768/32511613-9a4243ca-c3f4-11e7-9e1c-6dea8ed2a621.jpg)

**Comment by maciejtarmas** [comment]
Zrobione :)
