### ISSUE TITLE
elementy irytujące na olx

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#11]
Po wyłączeniu " moje filtry " zauważyłem że na olx panuje chaos, niewiem tak ma być czy niezaglądasz na olx-a?

![olx](https://user-images.githubusercontent.com/23176832/32752608-15212f6e-c8ca-11e7-94b2-d9df41369398.png)

**Comment by maciejtarmas** [comment]
Ale masz włączonego AlleBlocka? Bo pożyczkę, tooltipa i reklamę aplikacji miałbyś wywaloną.

**Comment by blocker999** [comment]
Sorry rzeczywiście przeglądarki mi się pomyliły, natomiast dalej są wyróżnij i odśwież szczerze niewiem poco chyba żeby wqrzać ludzi no i jeszcze bym wywalił fotki ( nad imieniem, po prawo)  bo są one rzadko i rozpraszają uwage.


![olx1](https://user-images.githubusercontent.com/23176832/32774629-2d06c752-c92d-11e7-9855-6451fdcea1d5.png)

**Comment by maciejtarmas** [comment]
Fotki zostawię. Ktoś najwyraźniej bardzo chce się zaprezentować, to niech ma możliwość.

Natomiast przyciski przed chwilą usunąłem.
