### ISSUE TITLE
bug na olx

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#12]
Wchodząc na olx.pl mam dziwny defekt otóż nie działa mi sortowanie po województwach lub miastach - to u góry, niewiem czy to tylko umnie czy jest to powszechne a jeśli tak to czy możesz to jakoś łatwo naprawić?, wiem że to robota dla admina ale zależy mi na czasie.
Sprawdzane na wielu przeglądarkach bez ublocka i dalej  to samo.

**Comment by maciejtarmas** [comment]
W sensie że ci się resetuje ustawienie województwa na górnej belce? Ten typ tak ma. Prawdopodobnie mają jakieś ciacho, które zapisuje preferencje wyszukiwania, ale za szybko wygasa.

To jest w ogóle tak skopany portal, że głowa boli. W XXI wieku bazują layout na tabeli. Powinno się developerów tego badziewia kijem po piętach potraktować.

Zamykam, bo niestety nic z tym nie jestem w stanie zrobić.
