### ISSUE TITLE
olx - iryt

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#13]
Znalazłem kolejny element na olx co prawda żadko on się pojawia ale wkurza:
![olx - iryt](https://user-images.githubusercontent.com/23176832/34070836-d46d162e-e26c-11e7-8b87-1fe450db075b.png)

`##.offer-sidebar__box--flaggedads.offer-sidebar__box`

**Comment by maciejtarmas** [comment]
Za cholerę nie mogę na to trafić.

Może robią jakieś testy A/B przed zmianą layoutu?

Może wreszcie ktoś im powiedział, że w XXI wieku nie robi się stron na tabelkach i będą zmieniać ;]

Poczekam jeszcze trochę.

**Comment by maciejtarmas** [comment]
Dalej nie mogę trafić. Na razie zamykam.
