### ISSUE TITLE
olx - galeria ostatnio oglądanych

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#14]
Czemu blokujesz galerie ostatnio oglądanych na olx-ie tą pod ogłoszeniami, jest to bardzo pomocne wiem że można sprawdzić dane ogłoszenie w histori ale czasami i to niewiele da

`##div#favoritesGalleryBox`

**Comment by maciejtarmas** [comment]
Bardzo dużo osób prosiło o wywalenie ostatnio przeglądanych na Allegro, dlatego wywaliłem też na OLX. Nie wnikam dlaczego, ale ludzie chyba oglądają coś, czego partner/ka lub dziecko widzieć nie powinno ;]

Niestety, koncepcja osobnych kont użytkownika na komputerze nie jest jakoś wybitnie rozpowszechniona.

W każdym razie zostawię to tak, jak jest.
