### ISSUE TITLE
strona główna

### ISSUE THREAD

**Issue by ghost** [maciejtarmas/AlleBlock#15]
text `strona główna` uszkodzony, podobnie opis
![2018-01-26-https___alleblock pl_alleblock_alleblock txt](https://user-images.githubusercontent.com/5884000/35451333-28dbf5ba-02c3-11e8-8534-87586908c9a1.png)

**Comment by maciejtarmas** [comment]
Kodowanie znaków jest w UTF-8.

U ciebie prawdopodobnie wyświetla się jako ISO Latin 1.

Sprawdź, czy masz opcję zmiany kodowania znaków w przeglądarce. Coś w stylu menu Wygląd -> Kodowanie.

W każdym razie zamykam, bo to nie ma wpływu na działanie.
