### ISSUE TITLE
Adguard

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#17]
@maciejtarmas  FYI 
https://github.com/AdguardTeam/FiltersRegistry/commit/7a3c01059bf83f801eb3a4d4792123e3e8224ccd

**Comment by maciejtarmas** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/18

**Comment by maciejtarmas** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/19
