### ISSUE TITLE
Ublock Origin, AlleBlock i olx.pl

### ISSUE THREAD

**Issue by seba2282** [maciejtarmas/AlleBlock#18]
Witam. Odnośnie tego tematu, to mam problem. Zasubskryptowałem AlleBlock Filter do Ublock Origin i... Jak mój brat chciał odpowiedzieć na wiadomość prywatną jednego użytkownika olx.pl, to wysyłanie było blokowane przez UBO. Dopiero, jak dodałem olx.pl do wyjątków, można było wysyłać wiadomości. Więc moje pytanie. Czy ten filtr ma blokować całe olx.pl czy tylko irytujące elementy na nim? Czy można poprosić o przyjrzenie się temu problemowi i dać poprawkę? Pozdrawiam

**Comment by maciejtarmas** [comment]
Ciekawe. Do tej pory nie miałem problemów. W poniedziałek po południu potestuję.

**Comment by seba2282** [comment]
Będę czekać. :)

**Comment by maciejtarmas** [comment]
Tak się głupio składa, że nie za bardzo mam potrzebę kupienia czegokolwiek ;)

Masz może wystawione jakieś ogłoszenie, na które mógłbym wysłać testową wiadomość?

W razie czego linka poprosiłbym mailem na blablabla [małpa] alleblock [kropka] pl

**Comment by seba2282** [comment]
Niestety nie posiadam takowego ogłoszenia. Brat akurat próbował odpowiedzieć na prywatną wiadomość w sprawie oferty pracy (chyba to było, że poszukują dj na wakacje). I dopiero wyłączenie UBO załatwiło sprawę.

**Comment by maciejtarmas** [comment]
Wybacz za moje marne tempo odpowiedzi, ale cierpię ostatnio na brak wolnego czasu ;)

Sprawdzam sobie te wiadomości na OLX, ale jak na razie wszystko mi działa w obie strony.

Mam dość sporo reguł + dodatkowo Pi Hole jako globalny filtr zapytań DNS w całej sieci, więc stosunkowo ciężki setup.

Masz możliwość zrobienia zrzutu ekranu z logu uBlock przy wysyłaniu wiadomości przez OLX?

**Comment by seba2282** [comment]
Witam, ostatnio z dwa czy trzy razy była aktualizacja filtrów. Więc być może problem został naprawiony. Umówmy się tak. Jak brat będzie pisać w najbliższym czasie, to napiszę tutaj czy jest to naprawione. Nie ukrywam też, że korzystam z pozostałych filtrów z certyficate.it (nie działa już jakiś Adguard i cookies nie działa tylko z MS Edge). Oraz korzystam z pozostałych wbudowanych w ubo bez ignorowania filtrów kosmetycznych.

**Comment by maciejtarmas** [comment]
OK, na razie zamykam. Jakby co, to będziemy szukać dalej.
