### ISSUE TITLE
Invalid filter

### ISSUE THREAD

**Issue by WowDude** [maciejtarmas/AlleBlock#19]
Invalid filter https://github.com/maciejtarmas/AlleBlock/blob/476a9411966f6d533068abdf57f57a3a47b17ec6/alleblock.txt#L268

It seems that correct should be:
`allegro.pl##div[data-box-name="Ochnik.brandedshop.18.03.2018.section.wrapper"]`
`allegro.pl##div[data-box-name="RB.brandedshop.19.03.2018.section.wrapper"]`

**Comment by maciejtarmas** [comment]
Thanks.

I fixed it, but the rules were already obsolete anyway.
