### ISSUE TITLE
Brak galeri na olx

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#2]
![galeria na olx](https://user-images.githubusercontent.com/23176832/28516921-20df7fbe-7063-11e7-9355-1075ed6e2b02.png)
@maciejtarmas Czy brak galeri na głównej to efekt zamierzony?, bo jeśli tak to proponuje to odblokować.

**Comment by maciejtarmas** [comment]
Efekt zamierzony, ale chyba faktycznie odblokuję. Muszę na razie doczytać na jakich zasadach oferty pokazują się na stronie głównej.

**Comment by maciejtarmas** [comment]
OK, odblokowałem. Jak rozumiem, zwykły Kowalski może sobie wykupić takie promowanie, w odróżnieniu od np. Allegro, gdzie nie wiadomo na jakich zasadach i co jest promowane.
