### ISSUE TITLE
[allegro] brak ikon, nowy banner blik

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#23]
@maciejtarmas  witam, coś się popsuło ;) 

![screenshot_20180514_091728](https://user-images.githubusercontent.com/9846948/39983386-ce4a1e3a-5757-11e8-854b-6edc20ed9b26.png)

**Comment by maciejtarmas** [comment]
Banner wywaliłem w dzisiejszej porannej aktualizacji. Ikonom przyjrzę się wieczorem. Dzięki! :)

**Comment by maciejtarmas** [comment]
Załatwione.
