### ISSUE TITLE
Filtr blokuje Informacje o produkcie na Ceneo

### ISSUE THREAD

**Issue by bodywithoutorgans** [maciejtarmas/AlleBlock#29]
Jak w temacie, filtr ukrywa opis pojawiający się w zakładce "Informacje o produkcie" na stronie przedmiotu.

**Comment by krystian3w** [comment]
U mnie nie wycina.

**Comment by krystian3w** [comment]
`www.ceneo.pl#@#div[class*="lnd_article-main"]` ale nie odblokuje grafiki na prawo jak jest.

![preloader](https://camo.githubusercontent.com/1bd0582303efd3a466bf6937878250d21ae23248/68747470733a2f2f7777772e63656e656f2e706c2f636f6e74656e742f696d672f7072656c6f616465722e676966) |
--- |

 i tak cały czas.

**Comment by maciejtarmas** [comment]
Załatwiony punkt 1 i 2 :)
