### ISSUE TITLE
Brak pamięci na olx

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#3]
Mianowicie mam taki dość problem z` /js/tracking/*` który jest w EasyPrivacy, podczas przeglądania ogłoszeń na olx-ie gdy byłem na drugiej stronie z ogłoszeniami i wszedłem w jakieś ogłoszenie i  wyszedłem to wracałem z powrotem do pierwszej strony a powinienem przecież zostać przekierowany do ostatnio oglądanej czyli do drugiej, więc musiałem sobie dodać tą regułę do wyjątków.

Proszę sprawdź to bo być może taka ( irytująca ) sytuacja ma miejsce nie tylko u mnie.

**Comment by maciejtarmas** [comment]
Ta reguła blokuje to:

https://s1.olx.pl/static/olxpl/naspersclassifieds-regional/olxeu-atlas-web/static/js/tracking/ninja.js

I teraz ciekawe, bo pod Safari mi wszystko działa bez tego skryptu z AlleBlockiem, EasyPrivacy i innymi, ale Firefox wywala się z kompletnie wyłączonym uBlockiem i nie jestem w stanie nawet nawigować po kolejnych stronach, tylko przenosi mnie do góry po kliknięciu nr strony.

Jutro się temu bliżej przyjrzę.

**Comment by maciejtarmas** [comment]
@blocker999 

A teraz mi wszystko działa jak powinno. Normalnie używam Firefoksa tylko i wyłącznie z AlleBlockiem do testów, ale poszło nawet jak dorzuciłem EasyPrivacy do kompletu.

Zobacz może jak to działa u ciebie w trybie prywatnym, bo miałem taki moment w Firefoksie, kiedy w normalnym trybie nie działało, a prywatnym tak. Mimo wyczyszczenia całego cache i innego bajzlu.

Wydaję mi się, że w OLX coś kombinowali.

**Comment by blocker999** [comment]
W prywatnym to samo no ale faktycznie problem występuje na Firefoxie i firefoxopodobnych tzn ja tylko sprawdzałem oprócz niego też Cyberfox i dalej to samo, problem ustępuje po dodaniu wyjątku do `/js/tracking/*`

Niewiem czy to wina olx czy firefoxa ale chyba warto dodać do listy `@@/js/tracking/*` bo ludzie mają różne filtry i przeglądają olx-a na różnych przeglądarkach.

**Comment by blocker999** [comment]
``

**Comment by maciejtarmas** [comment]
Mógłbyś zobaczyć teraz, czy działa?

Wrzuciłem aktualizację, w której odblokowałem te 2 skrypty:

https://s1.olx.pl/static/olxpl/naspersclassifieds-regional/olxeu-atlas-web/static/js/tracking/ninja.js
https://s2.olx.pl/static/olxpl/naspersclassifieds-regional/olxeu-atlas-web/static/js/tracking/ninja-cee.js

Później sprawdzę, czy nie popsułem przy tym wersji mobilnej, ale to na razie nieistotne.

**Comment by blocker999** [comment]
OK, narazie jest poprawnie ale ewentualne o błędach zawsze mogę powiadomić.
