### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by hawkeye116477** [maciejtarmas/AlleBlock#30]
Zauważyłem, że masz w swoich filtrach regułę `allegro.pl##div[data-box-name="allegro.rodoConsentModal"]`. Jest już ona również w Polskich Filtrach RODO-Ciasteczkowych. Jednakże chodzi o to, że sama dodana powoduje zablokowanie scrolla. Więc jeżeli chcesz dublować, to proponowałbym dodanie również tej reguły => `||assets.allegrostatic.com/opbox-rodo-consent-modal/index*.css` :smile:.

**Comment by maciejtarmas** [comment]
Dziękować :)

**Comment by krystian3w** [comment]
śmiałkowie blokują plik JS i niby działa Allegro.

**Comment by maciejtarmas** [comment]
Do pewnego stopnia działa, ale np. na listach przedmiotów nie ładują się zdjęcia, więc niby da się używać Allegro z wyłączonym JS, ale pozbywamy się dość kluczowej funkcjonalności.

**Comment by krystian3w** [comment]
Mnie chodzi tylko o plik "`opbox-rodo-consent-modal/index*.js`" - ~~chociaż obecnie w loggerze nie widać by taki się ostał jako osobny~~.

---

Albo mam: np. `https://assets.allegrostatic.com/opbox-rodo-consent-modal/index__9c9b4ae2.js`

`https://pastebin.com/raw/SKt20Lr1`
