### ISSUE TITLE
wersja lite filtrów alleblock

### ISSUE THREAD

**Issue by ghost** [maciejtarmas/AlleBlock#31]
czy istnieje możliwość stworzenia lekkiej wersji filtrów alleblock dla użytkowników którzy nie chcą absolutnie wszystkiego blokować. https://github.com/MajkiIT/polish-ads-filter/issues/8965

**Comment by maciejtarmas** [comment]
Niestety, nie widzę opcji, żeby utrzymywać dwie wersje. Raz, że gdybym przepuścił część śmiecia, to zaraz pojawiłby się ktoś, kto chciałby, żebym przepuścił inną część, a tę wcześniejszą zablokował. Dwa, moja doba ma tylko 25 godzin, a i tak ledwo wyrabiam na zakrętach ;)

**Comment by ghost** [comment]
@maciejtarmas możesz zrobić whiteliste z podziałem na sekcje.

**Comment by KonoromiHimaries** [comment]
wyjątki możesz dodawać na bieżąco podczas dodawania nowych reguł więc nic cie to nie kosztuje.
