### ISSUE TITLE
wybrane dla ciebie - pozostałości

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#33]
![scr-1543152592-001](https://user-images.githubusercontent.com/9846948/48979677-c2f3a500-f0be-11e8-8a82-bede4e3eb6c9.png)

![scr-1543152781-001](https://user-images.githubusercontent.com/9846948/48979707-12d26c00-f0bf-11e8-9374-7ce1dd858989.png)

**Comment by maciejtarmas** [comment]
Możesz mi podać linka do strony gdzie to występuje?

**Comment by FadeMind** [comment]
Strona domowa **PO ZALOGOWANIU**.
![scr-1543173499-001](https://user-images.githubusercontent.com/9846948/48983449-45945880-f0ef-11e8-97b1-600a15b970a1.png)
![scr-1543173540-001](https://user-images.githubusercontent.com/9846948/48983454-6197fa00-f0ef-11e8-8ac6-87db41d56f72.png)

**Comment by maciejtarmas** [comment]
Ciekawe, u mnie tego nie widać. Mógłbyś skopiować mi kod strony i wrzucić tutaj?

**Comment by FadeMind** [comment]
@maciejtarmas proszę https://pastebin.com/bQKR1j81

**Comment by FadeMind** [comment]
@maciejtarmas  DZIAŁAJĄCE reguły dla Adguarda:

`allegro.pl##div[data-box-name="reco-cat1-container"][data-prototype-id="layout.container"][data-analytics-category="layout.container"]`

`allegro.pl##div[data-box-name="reco-cat2-container"][data-prototype-id="layout.container"][data-analytics-category="layout.container"]`

`allegro.pl##div[data-box-name="reco-cat3-container"][data-prototype-id="layout.container"][data-analytics-category="layout.container"]`

![scr-1543253399-001](https://user-images.githubusercontent.com/9846948/49031154-7fc23080-f1a9-11e8-8aaf-4c1f7f37fa22.png)


CC @adamwr

**Comment by maciejtarmas** [comment]
A zobacz taką pojedynczą regułę, bo to chyba jest wrapper dla tych wszystkich poszczególnych boksów:

`allegro.pl##div[data-box-name="reco-batch-main-container"]`

Dalej tego nie widzę ani pod Safari, ani pod Firefoksem.

**Comment by FadeMind** [comment]
> `allegro.pl##div[data-box-name="reco-batch-main-container"]` działa ;)

**Comment by maciejtarmas** [comment]
Dzięki bardzo, uaktulnione :)
