### ISSUE TITLE
allegro: premium.with.dfp

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#36]
![scr-1557930036-001](https://user-images.githubusercontent.com/9846948/57783101-d0185500-772d-11e9-876b-6dfd91bb3f44.png)

![scr-1557930097-001](https://user-images.githubusercontent.com/9846948/57783055-b7a83a80-772d-11e9-98ff-27b0bf8d76cd.png)

**Comment by FadeMind** [comment]
![scr-1557930475-001](https://user-images.githubusercontent.com/9846948/57783523-8f6d0b80-772e-11e9-9642-53f616089d2c.png)

**Comment by maciejtarmas** [comment]
Tych "Ostatnio przeglądanych" nie mogę wyłapać w naturze. Mógłbyś podesłać mi linka?

**Comment by FadeMind** [comment]
https://allegro.pl/oferta/dysk-ssd-samsung-860-evo-1tb-mz-76e1t0b-eu-7584236872

**Comment by maciejtarmas** [comment]
U mnie nie widać tych ostatnio przeglądanych. Pewnie znowu coś testują. W każdym razie i tak zablokowałem. Dzięki!
