### ISSUE TITLE
OLX - ING

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#37]
Kredyt ( na dole w ogłoszeniach )

![olx - ing](https://user-images.githubusercontent.com/23176832/58382769-c8c73600-7fce-11e9-9be1-998f8337e2ee.png)

**Comment by maciejtarmas** [comment]
Na chwilę obecną wyskakuje mi tylko jeśli wyłączę listę. Fałszywy alarm?
