### ISSUE TITLE
otomoto - finanse

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#38]
Finanse ( pod opisem w ogłoszeniach )

![finanse](https://user-images.githubusercontent.com/23176832/58382863-b7caf480-7fcf-11e9-9b04-4bab448d566a.png)

**Comment by maciejtarmas** [comment]
Tego też nie widzę.

**Comment by maciejtarmas** [comment]
A, sorry. Otomoto jeszcze nie ruszałem.
