### ISSUE TITLE
Gdzie jest sprzedajemy.pl?

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#4]
Przeglądając paczke alleblocka zauważyłem że w planach są filtry do" Gumtree " a do " Sprzedajemy. pl ", nie ( co mnie zdziwiło ), gdyż ten serwis jest dość popularny wśród Polaków a dzięki wprowadzeniu przez olx-a opłat za niektóre ogłoszenia, coraz bardziej zwiększa się liczba użytkowników.

https://toczytam.pl/porownanie-serwisow-ogloszeniowych-w-polsce/

Dlatego pytam kiedy i czy wogóle są plany aby i go wprowadzić na liste?.

**Comment by maciejtarmas** [comment]
Dorzucam do listy serwisów, które prędzej czy później zrobię.

Co do terminu się nie określę na razie.

**Comment by maciejtarmas** [comment]
Raptem niewiele ponad 30 reguł najwyraźniej wystarcza, żeby sprzedajemy.pl doprowadzić do porządku :)

Wrzucam wersję testową, jeśli masz ochotę się pobawić:

https://alleblock.pl/alleblock/alleblock_sprzedajemy.pl.txt

Jeśli wszystko będzie OK, to w przyszłym tygodniu dorzucę ją do głównej listy.

**Comment by blocker999** [comment]
Dzięki przetestuje i odezwe się za pare dni.

**Comment by blocker999** [comment]
Ta lista chyba jest ok, więc warto ją dodać.

**Comment by maciejtarmas** [comment]
Zrobione.
