### ISSUE TITLE
OLX - NOTUS

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#44]
Kredyt
https://www.olx.pl/oferta/nowy-dom-103-4-m2-CID3-IDAgsNl.html#43de7db5fe;promoted

![notus](https://user-images.githubusercontent.com/23176832/59196865-1d9eab00-8b90-11e9-8a55-c44e5f68dc92.png)

**Comment by maciejtarmas** [comment]
Robi się.
