### ISSUE TITLE
allegro.pl - błąd?

### ISSUE THREAD

**Issue by ggargul** [maciejtarmas/AlleBlock#45]
Nie jestem pewien ale to może być błąd, bo są usunięte same zdjęcia, a napisy + ceny nie, więc albo usunąć też napisy + ceny, albo przywrócić zdjęcia?

`https://allegro.pl/artykul/za-co-odpowiada-dpi-w-myszce-ZGzMYb68qhg`

z Alleblock
![ss_005](https://user-images.githubusercontent.com/51117730/59911178-a086f780-9413-11e9-95f9-cca22443aaba.png)

bez Alleblock
![ss_006](https://user-images.githubusercontent.com/51117730/59911190-a4b31500-9413-11e9-88e4-7accd2112770.png)

**Comment by maciejtarmas** [comment]
Dzięki. Po długim weekendzie uaktualnię.
