### ISSUE TITLE
dom-i-ogrod annoyances

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#46]
Źródła strony - https://www78.zippyshare.com/v/8hfgGmA8/file.html

![s](https://i.imgur.com/n4pAr8u.png)

Adblocker: Adguard dla Windows

Dodatkowo można usunąć obraz tła Oświetlenie.

**Comment by maciejtarmas** [comment]
Na razie zostawiam otwarte. Muszę znaleźć chwilę, żeby wszystkie kategorie posprzątać, a czasu jak na lekarstwo. Kwestia paru dni :)

**Comment by FadeMind** [comment]
@maciejtarmas 

`allegro.pl##div[data-box-name="allegro.login.smart.status"]`

link-reklama nad loginem ze smart.

**Comment by maciejtarmas** [comment]
https://github.com/maciejtarmas/AlleBlock/issues/48
