### ISSUE TITLE
AlleBlock - wkrótce zmiany

### ISSUE THREAD

**Issue by maciejtarmas** [maciejtarmas/AlleBlock#48]
Cześć.

Jak pewnie zauważyliście, ostatnio AlleBlocka traktowałem nieco po macoszemu.

Na ~~listopad~~ grudzień planuję reset koncepcji - lista będzie obejmować tylko Allegro i Allegro Lokalnie.

Niestety, z braku czasu nie jestem w stanie zajmować się innymi serwisami. Tak to jest, że czasami obowiązki zawodowe i rodzinne muszą wziąć górę nad hobbystyczną zabawą.

Planuję przejrzeć wszystkie reguły i zastosować więcej filtrów na konkretne elementy zamiast selectorów CSS, które są dość procesorożerne i spowalniają działanie.

Stay tuned!

**Comment by krystian3w** [comment]
Allegro "globalnie" dodało cookies:

` ||allegrolokalnie.pl/assets/cookies-info.js$script,domain=allegrolokalnie.pl `

**Comment by blocker999** [comment]
" Na listopad planuję reset koncepcji - lista będzie obejmować tylko Allegro i Allegro Lokalnie. "

Czy może być po staremu ? tzn Ceneo, eBay, OLX i Sprzedajemy i tak one niewymagają codziennego nadzoru,, prosze, to jak?

**Comment by krystian3w** [comment]
W sumie można by je przenieść w tryb legacy do nowego pliku z ostrzeżeniem o braku aktualizacji.

Opcjonalnie może ktoś zrobi fork i będzie mieć czas na naprawy.

**Comment by maciejtarmas** [comment]
Muszę to przemyśleć.

Może faktycznie wydzielę resztę do osobnej listy traktowanej z małym priorytetem.

**Comment by gargul2** [comment]
Projekt padł, ostatnia aktualizacja 13 miesięcy temu.

**Comment by maciejtarmas** [comment]
Bardziej twórca padł, tak bym to określił ;)

Generalnie sytuacja wygląda tak, że aktualnie sprawy codzienne zabierają mi zbyt dużo czasu i sił, żebym mógł jeszcze ogarnąć inne tematy.

Moja gehenna ma się ku końcowi, także myślę, że gdzieś we wrześniu zrobię reset i ruszymy od nowa.

Tymczasem, jeśli ktoś ma chęć, to mile widziany byłby jakiś pull request, który mógłbym wciągnąć do listy jako tymczasową protezę.

**Comment by seba2282** [comment]
"Moja gehenna ma się ku końcowi, także myślę, że gdzieś we wrześniu zrobię reset i ruszymy od nowa."

@maciejtarmas Trzymam za słowo.

**Comment by gargul2** [comment]
https://allegro.pl/artykul/routery-z-qos-jak-dzialaja-113739

![capture_022_28-07-2020_13-30-20](https://user-images.githubusercontent.com/63287518/88660253-ae0eb680-d0d6-11ea-9fc0-b25d048f6d8f.gif)

**Comment by gargul2** [comment]
Maciek, kienci się skarżą - https://github.com/MajkiIT/polish-ads-filter/issues/16998

**Comment by seba2282** [comment]
@maciejtarmas, co w końcu z filtrem Alleblock?

**Comment by gargul2** [comment]
Jeśli Maciek tego już nie będzie prowadził to może chłopaki z [repo EI](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters) przygarną Alleblock do siebie, podobnie jak przygarnęli KAD.

**Comment by seba2282** [comment]
@gargul2 KAD ma 26 tysięcy reguł. Filtry Wewnętrzne chyba dołączają do web annoyances ultralist.

**Comment by krystian3w** [comment]
* `Wewnętrzne` zdechły - jedyny wciągnięty moduł to jako-tako  w Polskie EI "**prenumerat**" (przejrzałem filtry do mniej-więcej połowy) na chęć `blockera99` (możliwe, że do zadecydowało o kasacji), jest jakaś kopia z maja (?), AdGuard ma swoją ostatnią z 26 lipca.

* Ja nie widzę opcji by `Wewnętrzne` wcielić w Polskie EI lub zrobić jako kolejne repozytorium, na pewno nie ma chęci do napraw nawigacji ruchomych, EI już się nie chce nimi na 100% zajmować (stąd próba przywrócenia ich do "`Ultra Web Annoyance`").

> Filtry Wewnętrzne chyba dołączają do `web annoyances ultralist`

tylko te nawigacje "latające", jak ktoś w końcu zrobi PR aktualizując ich stan na 2020, np. `natemat.pl` kolejny raz zmienił layout i trzeba w filtrach dla nich kolejne korekty.

Filtrów "modułów" np.:
`anti-donate-filters`
`anti-mob-elements`
`e-commerce-filters`
`paid-subscriptions`
`unattractive-domians`
`unexpected-static-element`

Nie zaproponowano by je wcielić w `web annoyances ultralist`.

Zaciągane inne listy "HOSTS" zostaje ręcznie dodać jako zbiór linków.

`zewnetrzne.txt`
```diff
! Source: https://github.com/piperun/iploggerfilter/blob/master/filterlist
! Source: https://github.com/HexxiumCreations/threat-list/blob/gh-pages/hexxiumthreatlist.txt
-! Source: https://github.com/PolishFiltersTeam/KAD/blob/master/KAD.txt
-! Source: https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/blob/master/polish_rss_filters.txt
-! Source: https://github.com/olegwukr/polish-privacy-filters/blob/master/adblock.txt
! Source: https://github.com/metaphoricgiraffe/tracking-filters/blob/master/trackingfilters.txt
! Source: https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt
```

---

Propozycji na przeniesienie AlleBlock do `PolishFiltersTeam` na podobnych zasadach jak z KAD - też nie otrzymaliśmy.

**Comment by gargul2** [comment]
> Ja nie widzę opcji by `Wewnętrzne` wcielić w Polskie EI lub zrobić jako kolejne repozytorium, na pewno nie ma chęci do napraw nawigacji ruchomych, EI już się nie chce nimi na 100% zajmować (stąd próba przywrócenia ich do "`Ultra Web Annoyance`").

Nie szkodzi, bo to ja się niezbyt jasno wyraziłem, wspominając o Filtrach Wewnętrznych chodziło mi w zasadzie tylko lub przede wszystkim o Reklamy Wewnętrzne i Anty-Donacje, zupełnie zapomniałem, że tam były jakieś inne rzeczy jak np. nawigacje ruchome, one są teraz w `Ultra Web Annoyance` i niech tam zostaną jak najbardziej, zgadzam się z tym. Tak więc jeszcze raz chciałem podkreślić - chodziło mi głównie o:
- Reklamy Wewnętrzne https://raw.githubusercontent.com/prinze06188/PolishSubFilters/master/internal-filters/wewnetrzne.txt
- Anty-Donacje https://raw.githubusercontent.com/prinze06188/PolishSubFilters/master/internal-filters/anti-donate-filters/anty-donacje.txt

Da radę to wcielić do EI czy są wg. was przestarzałe (zdechły), ale nawet jak za stare to po prostu od nowa zacząć je w EI?

**Comment by seba2282** [comment]
@krystian3w, Adguard wywalił już wewnętrzne z listy filtrów.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/382/files raczej dużo nie daje: 

![obraz](https://user-images.githubusercontent.com/35370833/93117835-b2f7eb80-f6bf-11ea-84e4-cb5e458bf263.png) |
--- |
Sta&shy;ry do&shy;da&shy;tek da&shy;lej wi&shy;dzi lis&shy;tę, w naj&shy;gor&shy;szym wy&shy;pa&shy;dku zni&shy;knie od 3.6 lub zmia&shy;ny na inny po&shy;mysł pe&shy;wnie np. "`Mochi filters`".

**Comment by blocker999** [comment]
Jest połowa Września, więc narazie niema co dyskutowć o losach alleblocka a jeśli o wewnętrzne chodzi to zapraszam do  : https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2507

**Comment by krystian3w** [comment]
Jest, to nie zawieszenie od sierpnia 2020 a czerwca 2019 - ludzie boją się jak przez 2 tygodnie nie ma aktualizacji lub SSL walnie w domenie i listy nie umieją pobrać.

**Comment by gargul2** [comment]
Jako, że nie odpowiedziano mi na [pytanie](https://github.com/maciejtarmas/AlleBlock/issues/48#issuecomment-692168460) (to pierwsze), to sam sobie odpowiedziałem: 
- reklamy premium, prenumeraty, alledrogo, to wszystko są rekl. wewnętrzne

I teraz tak to wygląda:
- na repo EI blokowane są `Prenumeraty` wszystkie (poza sklepami, księgarniami itp.)
- na repo Alledrogo blokowane są `Reklamy Wewnętrzne / Oferty / Promocje` na 3 największych portalach
- na repo Reklam blokowane są `Premium` jedne tak, inne nie, wg. nieznanego widzimisię admina

Czyli wewnętrzne są rozsypane na 3 różne repozytoria.

**Comment by gargul2** [comment]
Alleblock już jest przestarzałe, część rzeczy jest jeszcze blokowana, ale niektóre reklamy i rzeczy wyciekają:

![Screenshot_2020-09-22 Allegro - atrakcyjne ceny](https://user-images.githubusercontent.com/63287518/93864395-205dda80-fcc5-11ea-97f3-cc5d92b12a16.png)

**Comment by seba2282** [comment]
@krystian3w serio nie da się dorzucić te 500 reguł np. w irytujące i kontynuować projekt? 

@maciejtarmas Co z tobą? Ludzie się dopytywują czy AlleBlock jest martwy czy będzie kontynuowany. Chcemy oficjalne info.

**Comment by gargul05** [comment]
Jak widać, w tym przypadku brak odpowiedzi jest odpowiedzią, lista oficjalnie umarła śmiercią naturalną i jest nie wspierana.

**Comment by seba2282** [comment]
@krystian3w, możecie jakoś sforkować reguły albo dodać do filtrów i wspierać? To powinno być w kategorii irytujące, tak sądzę.

**Comment by krystian3w** [comment]
Nie, ja nie wyczuwam jak ukrywać oferty promowane, sponsorowane to niby co 3 tygodnie łatwo ukryć, bo mają atrybut "`isSponsoredItem`".

**Comment by seba2282** [comment]
> Nie, ja nie wyczuwam jak ukrywać oferty promowane, sponsorowane to niby co 3 tygodnie łatwo ukryć, bo mają atrybut "`isSponsoredItem`".

Skoro to takie łatwe, to czemu nie dodasz tego jako irytujące?

**Comment by krystian3w** [comment]
Bo  potem trzeba będzie ukryć te promowane, co za bardzo oznakowania nie mają.

**Comment by seba2282** [comment]
> Bo  potem trzeba będzie ukryć te promowane, co za bardzo oznakowania nie mają.

Czyli co? Zostajemy na lodzie z serwisami typu Allegro i itp.?

**Comment by zaba-monika** [comment]
Alleblock już nie trzyma, jest przestarzałe, lista jest oficjalnie martwa:
- wyskakują Oferty Sponsorowane jak w https://github.com/MajkiIT/polish-ads-filter/issues/16998
- wyciekają reklamy jak na poniższym zrzucie ekranu:

<details not-open>
<summary>screenshoot</summary>


![Screenshot_2020-10-17 Allegro - atrakcyjne ceny](https://user-images.githubusercontent.com/72980128/96333816-52681f80-106c-11eb-8c42-8852a8863c3b.png)

</details>

**Comment by seba2282** [comment]
@krystian3w co dalej z serwisami Allegro, itp.? Widzisz, że autor Alleblock porzucił projekt.

**Comment by hawkeye116477** [comment]
Po prostu @seba2282 zrobi forka i będzie dalej kontynuował zabawę...

**Comment by seba2282** [comment]
> Po prostu @seba2282 zrobi forka i będzie dalej kontynuował zabawę...

@hawkeye116477 To ci się udało. 😂😂😂

**Comment by seba2282** [comment]
Zmian się nie doczekaliśmy. Myślę, że Alleblock jest martwy (albo nie wiem).

**Comment by zaba-monika** [comment]
To myślisz tak samo jak ja myślałam już od ponad kilku miesięcy:

> zaba-monika : https://github.com/maciejtarmas/AlleBlock/issues/48#issuecomment-710784151 : Alleblock już nie trzyma, jest przestarzałe, lista jest oficjalnie martwa (...)

**Comment by hawkeye116477** [comment]
A co tu było się spodziewać, już rok minął od ostatniego commitu, więc raczej EOL. A kiedyś może ktoś jeszcze zrobi remake'a/reboota.

**Comment by seba2282** [comment]
@hawkeye116477 Co w takim razie z reklamami na allegro, otomoto, itp.?

**Comment by hawkeye116477** [comment]
Zostaną tam, no chyba, że @seba2282 zrobi remake'a AlleBlocka i po sprawie :smile:

**Comment by seba2282** [comment]
@hawkeye116477, ale wiesz że ja jestem kiepski w te klocki z regułami. 😂😂😂
