### ISSUE TITLE
nowa grafika na allegro

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#5]
na allegro pojawiła się nowa szata graficzna a wraz z nią wiele niespodzianek, szczególnie to widać na głównej, najlepiej by było byś to sam zobaczył.

**Comment by maciejtarmas** [comment]
Śledzę temat.

Podobno wczoraj mieli całkowicie zakończyć roll out, ale u mnie nadal wyświetla się stara wersja.

**Comment by blocker999** [comment]
Dobra masz racje sprawdzałem allegro na kilku przeglądarkach i rzeczywiście tam jest stara wersja ale na Slimjet widnieje umnie nowa : 

![nowa szata - allegro](https://user-images.githubusercontent.com/23176832/30319635-b07f12b4-97b0-11e7-8e7a-6a4338f9c1f9.png)

**Comment by maciejtarmas** [comment]
A mógłbyś gdzieś mi wrzucić kod źródłowy strony głównej? Pooglądałbym sobie przynajmniej na razie.

**Comment by blocker999** [comment]
Niema problemu tylko w czym podesłać lub w co wrzucić?
Może prościej samemu to przejrzeć na Slimjecie: http://www.slimjet.com/en/dlpage.php

**Comment by maciejtarmas** [comment]
Mam awersję do Chromium i pochodnych ;)

Możesz wkleić kod do nowego pliku w Gist i udostępnić link:
https://gist.github.com/

**Comment by blocker999** [comment]
https://gist.github.com/blocker999/16ed82866e325b674a9a92a7af126425

**Comment by maciejtarmas** [comment]
Dzięki :)

Parę zmian będę mógł wprowadzić na sucho, zanim jeszcze to szerzej rozpropagowali.

**Comment by blocker999** [comment]
OK ,pośpiechu niema.

**Comment by maciejtarmas** [comment]
Mała aktualizacja dotycząca sytuacji z nowym layoutem Allegro.

Miał podobno wg mojego info wejść o wiele wcześniej, ale nadal w różnych miejscach mam nowy, a w innych stary. I tak na razie będzie.

Na razie w liście dodałem sobie sekcję, gdzie mam nowy layout i część reguł przeniesionych ze starego wyglądu. Stąd np. w konfiguracji uBlock można zaobserwować, że liczba wykorzystywanych reguł jest mniejsza niż dostępnych. Niektóre się po prostu dublują.

Nie ma to wpływu na szybkość działania, bo zduplikowane reguły są po prostu olewane przez wtyczkę.

W każdym razie dopóki Allegro nie wprowadzi wszędzie nowego layoutu, dopóty muszę utrzymywać reguły dla dwóch różnych wersji.

**Comment by blocker999** [comment]
Fajna reklama się pojawiła ostatnimi czasy:

![allegro - visa](https://user-images.githubusercontent.com/23176832/33938944-920eee8e-e009-11e7-81b6-8aebb9984ec8.png)

**Comment by maciejtarmas** [comment]
Dzięki, wywalone :)

Na razie nie zamykam tego błędu. Muszę w końcu skonsolidować reguły ze starego i nowego layoutu Allegro, ale jakoś nie mogę znaleźć czasu.

**Comment by blocker999** [comment]
Coś nowego : 

![allegro](https://user-images.githubusercontent.com/23176832/37556827-a038325e-29fb-11e8-93bc-cf5bc02380a0.png)

**Comment by maciejtarmas** [comment]
Masz wersję listy 20180316a?

**Comment by blocker999** [comment]
Jest ok, poprostu miałem nieaktualne filtry.

**Comment by maciejtarmas** [comment]
https://github.com/maciejtarmas/AlleBlock/commit/0383c2bb9a123415bb762da204581765bd679b45
