### ISSUE TITLE
Allegro.pl

### ISSUE THREAD

**Issue by krystian3w** [maciejtarmas/AlleBlock#50]
pod niemal dowolną ofertą:

`allegro.pl##div[data-box-name*="carousel_ads"]`

**Comment by seba2282** [comment]
@krystian3w Dałbyś to w filtry irytujące w takim razie? Albo w dodatek antyirytujący specjalny? Jak widać, @maciejtarmas chyba zabił projekt. :)

**Comment by krystian3w** [comment]
Ale przecież masz AdGuard Base, to filtr od nich a @majkiit odrzucił dodanie.

**Comment by seba2282** [comment]
@krystian3w Czyli Adguard jest lepiej zorganizowany? Jak można odrzucić, skoro to podstawa polskich filtrów? Czyli można spokojnie już wywalać listę alleblock? Czy coś jeszcze tam blokuje przestarzale?

**Comment by krystian3w** [comment]
Chodzi mi, że @majkiit luki nie zredukował ani nie zrobił by załadowała się tam poprawnie karuzela z elementami sponsorowanymi blokowana przez np. EasyList.

**Comment by seba2282** [comment]
@krystian3w, na otomoto.pl też reklamy. Jest antyirytujący dodatek do usuwania pozostałości. Dlaczego @MajkiIT nie chce dodać reguł alleblock?

**Comment by MajkiIT** [comment]
@seba2282 nie wszystko może wylądować w listach. Później ludzie mają pretensje. Może zajmiesz się rozwojem filtrów Alleblock i nie trzeba będzie wyłączać.

**Comment by FadeMind** [comment]
@krystian3w  @maciejtarmas  @seba2282  @MajkiIT  stan na dzisiaj:
https://i.imgur.com/aS6bQ98.png

**Comment by seba2282** [comment]
@FadeMind Nie powiem, wygląda to pięknie. 😂😂😂  


@maciejtarmas daj znak życia i powiedz oficjalnie co dalej z Alleblock list.

**Comment by seba2282** [comment]
||a.allegroimg.com/original/*$image
allegro.pl##._f3a7b_3qYQB._f3a7b_2ht9F.mefy_5r.mlmm_56.m389_6m.mjb5_pa.mnjl_0.mp7g_oz.mpof_ki

Testuję z wyłączonym filtrem od alleblock, @FadeMind 

P.S. Teraz mi nie działa.

**Comment by seba2282** [comment]
@AdamWr Adguard ma jakieś reguły dla stron allegro, otomoto, itp.?

**Comment by krystian3w** [comment]
dla otomoto raczej nie, pod allegro jakieś są:

https://github.com/AdguardTeam/AdguardFilters/search?q=allegro.pl

(self-promo, mobilna apka, cookies, naprawa anty-adblock, naprawa działania aplikacji mobilnej).

**Comment by seba2282** [comment]
@krystian3w ta reguła na carousel ads nie działa (przynajmniej dla mnie).

**Comment by krystian3w** [comment]
Może jest nowa karuzela, od 31 dni jest nowy system reklam "wewnętrznych" na allegro.

**Comment by seba2282** [comment]
@krystian3w wiem gdzie leżą te reklamy.  Moment działały te reguły, co podałem. Ale teraz nie działają i reklamy wróciły.
