### ISSUE TITLE
AlleBlock powoduje błąd wyświetlania obrazów

### ISSUE THREAD

**Issue by jangromadowski** [maciejtarmas/AlleBlock#52]
Nie wyświetlają się powiększone obrazy po lewej stronie ogłoszenia.
FF 84.0.2 (64bity) uBlock

**Comment by krystian3w** [comment]
https://github.com/maciejtarmas/AlleBlock/blob/ce2e5dff40b2729118be5ec242ba60084e34f39b/alleblock.txt#L73

przykładowy obrazek:
`https://a.allegroimg.com/original/031713/cd3638e84913ae8028a6347d6e38/U-POL-RAPTOR-srodek-ochrony-4but-CZARNY-pistolet`

Inne działają, bo używają:

`e.allegroimg.com`...

**Comment by Joduai** [comment]
Obrazy w galeriach aukcji całkowicie przestały się wczytywać i wyświetlać kilka dni temu.
Podejrzewałem samego ublocka origin, ale miał aktualizację ze 2-3 dni temu i dopiero teraz zreflektowałem się, że to nie wina samego ub.
Po wyłączeniu filtra alleblock galerie w aukcji działają.

FX 84.0.2 x64 + win10

@jangromadowski ty masz na myśli większe zdjęcie po najechaniu na miniaturę na liście aukcji czy już w ogłoszeniu?

**Comment by krystian3w** [comment]
Większe zdjęcie.

Pierwsze zazwyczaj ma adres z subdomeny `a.allegroimg.com`.

W moje filtry pomaga:

```
||a.allegroimg.com/original/*$domain=allegro.pl,badfilter
```

**Comment by maciejtarmas** [comment]
W poniedziałek będę ogarniał. Z tego co na szybko zauważyłem, to z allegroimg.com trzeba by chyba blokować konkretne katalogi. Ewentualnie zablokować całość i odblokować te katalogi, które są potrzebne. Dużo syfu się stamtąd zaciąga.

**Comment by tomkc** [comment]
> W poniedziałek będę ogarniał. Z tego co na szybko zauważyłem, to z allegroimg.com trzeba by chyba blokować konkretne katalogi. Ewentualnie zablokować całość i odblokować te katalogi, które są potrzebne. Dużo syfu się stamtąd zaciąga.

Dodatkowo nie wyświetla się treść powiadomień od allegro po kliknięciu na ikonę dzwonka u góry-> pojawia się pusty box z miejscem na treść

**Comment by maciejtarmas** [comment]
Zamykam, bo to już mamy chyba posprzątane?

**Comment by krystian3w** [comment]
Tak od 45 dni naprawione pod każdą aukcję.
