### ISSUE TITLE
allegro-smart banners

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#53]
`https://allegro.pl/moje-allegro/zakupy/allegro-smart`

![20210124-1611495172-001](https://user-images.githubusercontent.com/9846948/105631944-3802c680-5e51-11eb-8704-4a94798c1705.png)
![20210124-1611495146-001](https://user-images.githubusercontent.com/9846948/105631946-39cc8a00-5e51-11eb-9fd3-ec5656d46fdc.png)

co ciekawe odnośnik `https://allegro.pl/strefaokazji/smartokazje` otwiera pustą stronę (co jest świetne xD) 

![20210124-1611495337-001](https://user-images.githubusercontent.com/9846948/105632032-8021e900-5e51-11eb-98b8-10c20ed6f4fd.png)

**Comment by krystian3w** [comment]
`##div[data-box-name^="mysmart"] + div + div` albo:

`##div[data-box-name^="mysmart"]:nth-child(1) ~ div:nth-child(3)` / `##div[data-box-name^="mysmart"]:nth-of-type(1) ~ div:nth-of-type(3)`

(`-of-type` nie zawsze pokrywa się z `-child`)

innego punktu zaczepienia jako logiczny nie widzę.

**Comment by FadeMind** [comment]
@krystian3w 
![20210124-1611507556-001](https://user-images.githubusercontent.com/9846948/105637452-e6b50000-5e6d-11eb-8a39-4fed3fbca1af.png)

```
allegro.pl##div[data-box-name="deals"]
```
`mysmart` nie działa. Nie wiem tylko czy uwalenie `deals` nie robi krzywdy gdzieś indziej. 🤔 

![20210124-1611508002-001](https://user-images.githubusercontent.com/9846948/105637699-013ba900-5e6f-11eb-9589-f370e234c27d.png)
