### ISSUE TITLE
allegro.user.inbox jest puste 

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#54]
@maciejtarmas dostajesz powiadomienie na Allegro, ale nie ma go na liście xD

![20210203-1612345992-001](https://user-images.githubusercontent.com/9846948/106729812-33d36780-660e-11eb-91e7-4ab80fbfca2d.png)

`data-box-name="allegro.user.inbox"`

**Comment by maciejtarmas** [comment]
Zrobione. Chciałem iść na łatwiznę i zrobiłem zbyt ogólny selector :)
