### ISSUE TITLE
Hamburger menu jest wybrakowany

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#55]
@maciejtarmas 

Menu w hamburgerze jest wybrakowane jak jest aktywna lista. 
Czerwonym zamieniłem miejsce na dane konta. 

![20210310-1615384755-001](https://user-images.githubusercontent.com/9846948/110640890-a5747780-81b1-11eb-8feb-31cbcffda321.png)
![20210310-1615384737-001](https://user-images.githubusercontent.com/9846948/110640894-a60d0e00-81b1-11eb-8e04-85c543780475.png)

**Comment by maciejtarmas** [comment]
Dzięki, poprawione. Szczerze, to nie wiem po co to wywaliłem :)
