### ISSUE TITLE
Allegro wykrywa blokowanie?

### ISSUE THREAD

**Issue by PabloVitasso** [maciejtarmas/AlleBlock#56]
![image](https://user-images.githubusercontent.com/4544017/114555708-41d5e200-9c68-11eb-9140-69c94b513b2b.png)

pojawia się po kliknięciu na dowolny produkt.

Firefox 87
uBlock Origin 1.34

jedyne co widzę to 
https://js.datadome.co/tags.js
https://www.googletagmanager.com/gtm.js

ale to już po wykryciu..

**Comment by FadeMind** [comment]
@pavelw podaj dokładną konfigurację uBlock i raport blokowania strony co jest blokowane, na podstawie jakich filtrów.

**Comment by maciejtarmas** [comment]
To mi bardziej wygląda na jakiś mechanizm blokujący podejrzaną aktywność na ich serwerze.

Masz możliwość połączenia się przez inną sieć? Jesteś w Play, więc prawdopodobnie nie masz własnego publicznego IP, tylko jesteś za NAT-em z innymi użytkownikami. Być może dzielisz IP z jakimś automatem do pobierania treści ofert czy czymś takim i cię zblokowali.

Nie jestem w stanie wymusić takiego komunikatu ani na FF z wyłączonym wbudowanym filtrem + uBO, gdzie mam tylko AlleBlock, ani na Safari + AdGuard z wieloma filtrami.

**Comment by PabloVitasso** [comment]
spróbuję odtworzyć na VM czysta instalacja FF.. może coś innego to powoduje (mam jeszcze LocalCDN, Privacy Badger i Spoof Timezone..). Występuje od dziś, sprawdzane na dwóch różnych sieciach - Play i Plus.

**Comment by PabloVitasso** [comment]
sprawcą okazała się wtyczka user agent switcher (https://gitlab.com/ntninja/user-agent-switcher)  ustawiona na Windows / Chrome 87. dzięki za pomoc! :)
