### ISSUE TITLE
opbox-advertisement-box psuje stronę produktu

### ISSUE THREAD

**Issue by FadeMind** [maciejtarmas/AlleBlock#57]
Reguła blokująca https://github.com/maciejtarmas/AlleBlock/blob/master/alleblock.txt#L145 
blokuje wyświetlanie szczegółów na temat sprzedawcy na stronie produktu.  

Problem był po włączeniu czarnego motywu w Stylus albo DarkReader. Niezwiązane z AlleBlock. Zamykam.

**Comment by maciejtarmas** [comment]
OK. Sam właśnie sprawdziłem i problem nie był po mojej stronie. Dzięki! :)
