### ISSUE TITLE
www.ceneo.pl

### ISSUE THREAD

**Issue by gomoku** [maciejtarmas/AlleBlock#6]
https://github.com/azet12/PopupBlocker/issues/121

**Comment by maciejtarmas** [comment]
Dzisiaj nie mam za bardzo czasu, żeby się tym zająć, ale jutro rano sprawdzę temat.

**Comment by maciejtarmas** [comment]
Nie jestem w stanie powtórzyć przewijania strony pod Firefoksem i Safari.

Druga kwestia to to, że na headerze jest przycisk, który robi dokładnie to co chcesz, czyli usadza całą belkę na górze. Twoja reguła jest teraz dodana do Popup Blocker PL, więc dopóki nie wyłączysz tej listy, to nie będziesz miał przycisku. Nie jestem zwolennikiem ingerowania w ten sposób, skoro samo Ceneo daje możliwość wyłączenia przewijanego headera  (@azet12, @hawkeye116477, @blocker999).

![screen shot 2017-09-21 at 06 58 14](https://user-images.githubusercontent.com/3435387/30679488-4bb76ae8-9e9a-11e7-9542-e78a953d6a53.png)

Ale dzięki, przy okazji grzebania w logach znalazłem XHR-a do wywalenia :)

**Comment by hawkeye116477** [comment]
@maciejtarmas Ja tam nawet bez naszych reguł nie widzę tego przycisku usadzającego, w takim razie masz jakąś inną wersję strony, której my nie mamy.

**Comment by maciejtarmas** [comment]
Spróbuj w trybie prywatnym albo wyczyść ciastka.

**Comment by hawkeye116477** [comment]
Ok, pojawiło się, ale musiałem schować sidebar.
