### ISSUE TITLE
Info o kredycie na OLX

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#7]
np tu: https://www.olx.pl/oferta/dzialka-inwestycyjna-gospodarstwo-CID3-IDoEAhU.html#f56ce9749e

![dzia](https://user-images.githubusercontent.com/23176832/31049265-02546d0e-a630-11e7-9bea-cb3c0edacb4a.png)

**Comment by maciejtarmas** [comment]
Dzięki, usunięte :)
