### ISSUE TITLE
olx - pop-up

### ISSUE THREAD

**Issue by blocker999** [maciejtarmas/AlleBlock#8]
Fajny pop-up jest po wysłaniu wiadomości.

![olx - pop-up](https://user-images.githubusercontent.com/23176832/31270801-18bec6b6-aa86-11e7-9552-f2162200f988.png)

**Comment by maciejtarmas** [comment]
Hmmm, u mnie jakoś nie chce wyskoczyć.

Wrzuciłbyś mi źródło strony, jak się pojawi u ciebie?

**Comment by blocker999** [comment]
Wysyłałeś wiadomość do innego użytkownika?, bo to tylko wtedy jest, być może jakaś reguła go łapie, sprawdź jeszcze raz.

**Comment by maciejtarmas** [comment]
No właśnie wysłałem przez stronę przedmiotu i potem z poziomu konta użytkownika i nic.

Sprawdzałem na Firefoksie, gdzie nie mam nic innego poza Alleblockiem.

**Comment by blocker999** [comment]
A jakiego blockera używasz ?, pytam bo sprawdzałem to Firefoxie z Ublockiem na drugim kompie i dalej to samo.

**Comment by maciejtarmas** [comment]
uBlock Origin. Dopiero dzisiaj pod Safari mi wyskoczyło.

Możesz zaktualizować listę i sprawdzić?

Wydałem nie do końca potrzebnie 150 zł, żeby to przetestować, więc lepiej żeby było OK :D

**Comment by blocker999** [comment]
No teraz jest idealnie a tak przy okazji zapytam na co poszła ta kasa bo czuje się winny.

**Comment by maciejtarmas** [comment]
Piąty access point Cisco Meraki MR18.

Solidny sprzęt i daje się przeflashować na OpenWrt/LEDE. Jak komuś wystarcza WiFi w standardzie N, to polecam :)
